# Generated by Django 3.1.4 on 2020-12-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smartphones',
            new_name='Smartphone',
        ),
    ]
